import { BitField } from './Bitfield';

export type IntentsString =
	| 'GUILDS'
	| 'GUILD_MEMBERS'
	| 'GUILD_BANS'
	| 'GUILD_EMOJIS'
	| 'GUILD_INTEGRATIONS'
	| 'GUILD_WEBHOOKS'
	| 'GUILD_INVITES'
	| 'GUILD_VOICE_STATES'
	| 'GUILD_PRESENCES'
	| 'GUILD_MESSAGES'
	| 'GUILD_MESSAGE_REACTIONS'
	| 'GUILD_MESSAGE_TYPING'
	| 'DIRECT_MESSAGES'
	| 'DIRECT_MESSAGE_REACTIONS'
	| 'DIRECT_MESSAGE_TYPING';

export class Intents extends BitField<IntentsString> {}
